### ISSUE TITLE
depends_on ... => :ruby

### ISSUE THREAD

**Issue by alyssais** [vitorgalvao/tiny-scripts#121]
Using any Homebrew command that parses all formulae (eg `brew uses`) causes errors from this tap.

```
Error: Failed to import: /usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/contagem-edp.rb
Calling 'depends_on ... => :ruby' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/contagem-edp.rb:3:in `<class:ContagemEdp>'
Please report this to the vitorgalvao/tiny-scripts tap!
Or, even better, submit a PR to fix it!
Error: Failed to import: /usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/olx-post.rb
Calling 'depends_on ... => :ruby' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/olx-post.rb:3:in `<class:OlxPost>'
Please report this to the vitorgalvao/tiny-scripts tap!
Or, even better, submit a PR to fix it!
Error: Failed to import: /usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/olx-prolongar.rb
Calling 'depends_on ... => :ruby' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/olx-prolongar.rb:3:in `<class:OlxProlongar>'
Please report this to the vitorgalvao/tiny-scripts tap!
Or, even better, submit a PR to fix it!
Error: Failed to import: /usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/pedir-gas.rb
Calling 'depends_on ... => :ruby' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/pedir-gas.rb:3:in `<class:PedirGas>'
Please report this to the vitorgalvao/tiny-scripts tap!
Or, even better, submit a PR to fix it!
Error: Failed to import: /usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/trello-purge-archives.rb
Calling 'depends_on ... => :ruby' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts/trello-purge-archives.rb:3:in `<class:TrelloPurgeArchives>'
Please report this to the vitorgalvao/tiny-scripts tap!
Or, even better, submit a PR to fix it!
```

**Comment by vitorgalvao** [comment]
Thank you, I’ve noticed this as well. It’s https://github.com/vitorgalvao/homebrew-tiny-scripts, to be more precise.

Haven’t yet decided how to fix that. I don’t really want to vendor the requirement, since it’s typically `watir` and I don’t want to spend my time getting a vendored gem up to date. The scripts themselves check for the existence of the gem, so I may just remove the line from the formulae and leave it at that. Formula dependence on gems was always a bit of hit or miss anyway (often it’s installed but recognised as if it isn’t).

I’ll likely do it tomorrow.

**Comment by vitorgalvao** [comment]
Done.

**Comment by alyssais** [comment]
> Thank you, I’ve noticed this as well. It’s https://github.com/vitorgalvao/homebrew-tiny-scripts, to be more precise.

Bah, of course it was.
