### ISSUE TITLE
Problem with comma after url

### ISSUE THREAD

**Issue by yurikoles** [vitorgalvao/tiny-scripts#67]
For example java-beta:
<details><summary>cask-repair java-beta</summary>

```
Type the new version (or leave blank to use current one, or use `s` to skip)
> 
Paste the new URL (or leave blank to use the current one)
> http://download.java.net/java/jdk8u152/archive/b02/binaries/jdk-8u152-ea-bin-b02-macosx-x86_64-27_mar_2017.dmg
Error: /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:14: syntax error, unexpected ':', expecting keyword_end
      cookies: { 'oraclelicense' => 'accept-securebackup-cookie' }
              ^
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:87:in `block in print_stanzas'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:83:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:83:in `print_stanzas'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:64:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:14: syntax error, unexpected ':', expecting keyword_end
      cookies: { 'oraclelicense' => 'accept-securebackup-cookie' }
              ^
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:87:in `block in print_stanzas'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:83:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:83:in `print_stanzas'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:64:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
==> Downloading external files for Cask ./java-beta.rb
Error: /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:14: syntax error, unexpected ':', expecting keyword_end
      cookies: { 'oraclelicense' => 'accept-securebackup-cookie' }
              ^
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/fetch.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/fetch.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/fetch.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
shasum: ==> Downloading external files for Cask ./java-beta.rb: 
Error: /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:14: syntax error, unexpected ':', expecting keyword_end
      cookies: { 'oraclelicense' => 'accept-securebackup-cookie' }
              ^
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:87:in `block in print_stanzas'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:83:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:83:in `print_stanzas'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb:64:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
diff --git a/Casks/java-beta.rb b/Casks/java-beta.rb
index 3b8c2b6b9..1e0c3fae0 100644
--- a/Casks/java-beta.rb
+++ b/Casks/java-beta.rb
@@ -1,8 +1,8 @@
 cask 'java-beta' do
   version '1.8.0_152-b02'
-  sha256 'a770c642f807f5f7f5f06598c2caef71611ee37a4ade976fdfab7ab15bfa7a15'
+  sha256 ''
 
-  url 'http://download.java.net/java/jdk8u152/archive/b02/binaries/jdk-8u152-ea-bin-b02-macosx-x86_64-27_mar_2017.dmg',
+  url 'http://download.java.net/java/jdk8u152/archive/b02/binaries/jdk-8u152-ea-bin-b02-macosx-x86_64-27_mar_2017.dmg'
       cookies: { 'oraclelicense' => 'accept-securebackup-cookie' }
   name 'Java Standard Edition Development Kit'
   homepage 'https://jdk8.java.net/download.html'
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
• url is probably incorrect, as a non-200 (OK) HTTP response code was returned (000)
• == java-beta.rb ==
E:  6: 14: unexpected token tCOLON
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)

1 file inspected, 1 offense detected
• 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) ^C
You aborted.
```
</details>

**Comment by vitorgalvao** [comment]
Fixed.
